"""Constants and configuration for plot rendering."""

# Plot sizing
PLOT_1D_MIN_WIDTH = 40
PLOT_1D_MAX_WIDTH = 80
PLOT_1D_HEIGHT = 15
PLOT_1D_DEFAULT_WIDTH = 60

PLOT_2D_MIN_WIDTH = 20
PLOT_2D_MIN_HEIGHT = 10
PLOT_2D_MAX_WIDTH = 80
PLOT_2D_MAX_HEIGHT = 30
PLOT_2D_DEFAULT_WIDTH = 60
PLOT_2D_DEFAULT_HEIGHT = 20

# Terminal aspect ratio (characters are ~2x taller than wide)
TERMINAL_ASPECT_RATIO = 2

# Data downsampling thresholds
DOWNSAMPLE_1D_THRESHOLD = 500
DOWNSAMPLE_2D_THRESHOLD = 100

# Defaults for unsupported data (same as 2D defaults)
DEFAULT_PLOT_WIDTH = PLOT_2D_DEFAULT_WIDTH
DEFAULT_PLOT_HEIGHT = PLOT_2D_DEFAULT_HEIGHT
